### ISSUE TITLE
🐛 BUG: asset URL Handling regarding site.url in preview mode

### ISSUE THREAD

**Issue by SrGeneroso** [kwchang0831/svelte-QWER#22] opened 2022-09-14 20:54 UTC
**Describe the bug**
Regarding ImageTool, Manifests, same origin policies and maybe partytown.
Some system is creating url for the images based on user/config/site.ts -> siteConfig.url parameter.
Running pnpm dev shows a couple of errors because is using the URL set in the config, although it should be using localhost/@imagetools...
If the default URL is used same origin police comes into work because the file is there since the default URL is the same as the demo deployed on vercel.
Finally, this is a little annoyance, if you pnpm build and preview those URLs points to the final URL that should be deployed but it's running also in localhost.
My workaround is to use localhost in the siteConfig.url

**To Reproduce**
1. Change siteConfig.url parameter on user/config/site.ts to somedomain.com
2. Run pnpm dev
3. See errors in console regarding properties from the manifest

**Environment (please complete the following information):**

- OS/Platform: [Windows/WSL]
- Browser [Brave]
- Versions

**Comment by kwchang0831** [comment] 2022-09-15 07:13
It is by design that required user to enter correct site.url. It is not a bug. 

However, it should handle better when user are running site in preview mode.

I will do it later.

**Comment by kwchang0831** [comment] 2022-09-15 18:15
I will close this issue for now till we have better solution to this.

**Closed by kwchang0831** 2022-09-15 18:15 UTC
Labels: invalid
